name: CI

on:
  push:
    branches: [ master, main, develop, feature/**, chore/**, bugfix/**, hotfix/**, misc/**]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            package.json
            package-lock.json
      - run: npm ci
      - run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3